# Generated by Django 4.1 on 2022-11-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='color',
            field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('P', 'Purple'), ('R', 'Red'), ('B', 'Blue')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='materia',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
